In [3]:
!pip install numpy

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 320.0 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 645.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.2/15.5 MB 5.3 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/15.5 MB 11.2 MB/s eta 0:00:02
   ----- ---------------------------------- 2.2/15.5 MB 17.2 MB/s eta 0:00:01
   -------- ------------------------------- 3.3/15.5 MB 18.9 MB/s eta 0:00:01
   -------- ------------------------------- 3.4/15.5 MB 15.6 MB/s eta 0:00:01
   ------------- -------------------------- 5.2/15.5 MB 19.3 MB/s eta 0:00:01
   ------------------ --------------------- 7.0/15.5 MB 22.4 MB/s eta 0:00:01
   --------------------- ------------------ 8.4/15.5 MB 23.5 MB/s eta 0:00:01
   ------------------------ --------------- 9.7/15.5 MB 23.8 MB/s eta 0:00:

In [4]:
import numpy as np

In [5]:
one_dimensional_arr = np.array([10, 12])
print(one_dimensional_arr)

[10 12]


In [6]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [11]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [13]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # Prints the data type of the array

['Welcome to Math for ML!']
<U23


In [14]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [15]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [16]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [17]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.90812447 0.73976024 0.14166181]


In [18]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [19]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
    one_dim_arr, (2, 3)  # the array to be reshaped  # dimensions of the new array
)
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [21]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [22]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

In [23]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [24]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

In [26]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [30]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


In [31]:
a

array([1, 2, 3, 4, 5])

In [28]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [29]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1 2 3]


In [32]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [33]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


In [36]:
# Note that a == a[:] == a[::]
print(a == a[:])
print(a == a[::])

[ True  True  True  True  True]
[ True  True  True  True  True]


In [37]:
# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [39]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


In [40]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
print(f"a1:\n{a1}")
print(f"a2:\n{a2}")

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [41]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [42]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
